version: '3.0'

services:
  magento-web:
    container_name: magento-web
    image: magentoweb:latest
    ports:
      - "80:80"
    volumes:
      - ./magento:/var/www/html
    links:
      - magento-db
    env_file:
      - build.env
  magento-db:
    container_name: magento-db
    image: mysql:5.6.23
    volumes:
      - ./db-data:/var/lib/mysql
    env_file:
      - build.env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - magento-db